---
title: "Choose I"
author: "The R Bootcamp <br/><a href='https://therbootcamp.github.io'>www.therbootcamp.com</a><br/><a href='https://twitter.com/therbootcamp'>@therbootcamp</a>"
date: "July 2018"
output:
  xaringan::moon_reader:
    css: ["default", "baselrbootcamp.css"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: '16:9'
---

layout: true

<div class="my-footer"><span>
<a href="https://therbootcamp.github.io/"><font color="#7E7E7E">Basel, July 2018</font></a>
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
&emsp;&emsp;&emsp;&emsp;&emsp;
<a href="https://therbootcamp.github.io/"><font color="#7E7E7E">www.therbootcamp.com</font></a>
</span></div> 

---



```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
# see: https://github.com/yihui/xaringan
# install.packages("xaringan")
# see: 
# https://github.com/yihui/xaringan/wiki
# https://github.com/gnab/remark/wiki/Markdown
options(width=110)
options(digits = 4)
```

# Choose your adventure!

.pull-left45[

<u>Base track</u><br>

<font size="8"><hfont>Practical - Case studies</hfont></font><br>

Work on one or all of 3 case studies designed to repeat the central elements of <high>Data I/O</high>, <high>Data Wrangling</high>, and <high>Statistics</high><br>

<high>Clinical trial</high>
Analyse a clinical trial comparing the effectiveness of drugs on reducing histamine.<br>
<high>Finance</high>
Study the development of key financial markets across the last 20 years<br>
<high>Sales</high>
Analyze sales from a real-world retailer across time and locations.<br>

]

.pull-right45[

<u>Advanced track</u><br>

<font size="8"><hfont>Machine Learning</hfont></font><br>

Learn... 

...when machine learning algorithms like <high>Random forests</high>, <high>Decisions trees</high>, and <high>Regression** work and why.

...how they are <high>implemented in R</high> to improve prediction performance in a real world data set.  

]




